### ISSUE TITLE
JbBindNet.js _processInvokeArgs error

### ISSUE THREAD

**Issue by yuzd** [mingyaulee/WebExtensions.Net#14]
![image](https://user-images.githubusercontent.com/16083659/141730852-af232e17-3f55-4e75-82ca-43e5c5639fa0.png)

**Comment by yuzd** [comment]
![image](https://dimg04.c-ctrip.com/images/0v50b1200094iwtibD627.png)

**Comment by mingyaulee** [comment]
I have fixed this issue in JsBind version 0.2.8, but for the PostMessage I will need to take some time to change how the APIs are generated in this package.

**Comment by yuzd** [comment]
@mingyaulee hi, how is the progress?

**Comment by mingyaulee** [comment]
Hi, unfortunately I have been finding it hard to make time for a refactoring. As of now maybe you would want to try out a workaround like:

```csharp
Any.From(port).InvokeFunction("postMessage", message);
```

**Comment by yuzd** [comment]
@mingyaulee 
The accesspath of multiple ports is the same

![image](https://dimg04.c-ctrip.com/images/0v56c120009598jql3AEC.png)

**Comment by mingyaulee** [comment]
Now I see what is happening here, it is a bug in JsBind which reuses the same guid every time the callback is executed. I will work on a fix for this over the weekend.

**Comment by yuzd** [comment]
ok thanks

**Comment by mingyaulee** [comment]
@yuzd The `Port.PostMessage` now accepts a `message` object as parameter in v0.10.1

**Comment by yuzd** [comment]
@mingyaulee great! thanks
