### ISSUE TITLE
Add Api for global keyboard event.

### ISSUE THREAD

**Issue by newbe36524** [mingyaulee/WebExtensions.Net#3]
It is wonderful that from 0.4 that some of callbacks are supported for browser API. I readly helps!

Is that possible to support some callbacks for `window` object like window.keydown window.keyup to support developer to handle keyboard event in browser extensions?

**Comment by mingyaulee** [comment]
That is possible, but right now the APIs that are returning a `window` object is not working yet because it is not serializable, which I think will be the next thing to work on after the next release.

**Comment by newbe36524** [comment]
Cool, I am looking forward to this plan

**Comment by mingyaulee** [comment]
I have just realised that maybe what you are expecting is kind of different from what I was thinking. 

My understanding is that you are thinking that the API to listen to window events should be provided within the extension Window API, but the thing is most of the Window API does not return the actual JavaScript `window` object. The only API I see that actually returns a JavaScript `window` object is the `Runtime.GetBackgroundPage` API which was what I was thinking instead.

In my opinion, this feature is not in the scope of extension API. It could be an entirely different library which interacts with the DOM from .Net, but I'm not excluding the possibility that it will be developed in this package in the future.

**Comment by newbe36524** [comment]
Yeah, maybe we can refer to a existing package or include it in this package in the future

**Comment by mingyaulee** [comment]
With [JsBind.Net](https://github.com/mingyaulee/JsBind.Net) it is extremely easy to create a binding to add such a listener. I do have a plan to create binding for the DOM related APIs but it will not be so soon. For now, these APIs will not be a part of this package so I will close this issue.

**Comment by newbe36524** [comment]
I think it should work https://github.com/jsakamoto/Toolbelt.Blazor.Hotkeys
